/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef QJULIA_H_TMP_
# define QJULIA_H_TMP_
# define VAR_OUTPUT "f"

static const char qjulia[] =
 "RWTexture2D<float4> f:register(u0);cbuffer cbCS:register(b0){float4 c_diffuse;float4 c_mu;float c_epsilon;int c_width;int c_height;int c_selfShadow;float4x4 rotation;float zoom;};"
 "float4 t(float4 f,float4 c)"
 "{"
   "float4 i;"
   "i.x=f.x*c.x-dot(f.yzw,c.yzw);"
   "i.yzw=f.x*c.yzw+c.x*f.yzw+cross(f.yzw,c.yzw);"
   "return i;"
 "}"
 "float4 t(float4 f)"
 "{"
   "float4 c;"
   "c.x=f.x*f.x-dot(f.yzw,f.yzw);"
   "c.yzw=2*f.x*f.yzw;"
   "return c;"
 "}"
 "float3 n(float3 f,float4 c)"
 "{"
   "float3 i;"
   "float4 n=float4(f,0);"
   "float w,r,u;"
   "float4 x=n-float4(.0001,0,0,0),b=n+float4(.0001,0,0,0),e=n-float4(0,.0001,0,0),z=n+float4(0,.0001,0,0),y=n-float4(0,0,.0001,0),d=n+float4(0,0,.0001,0);"
   "for(int h=0;h<10;h++)"
     "x=t(x)+c,b=t(b)+c,e=t(e)+c,z=t(z)+c,y=t(y)+c,d=t(d)+c;"
   "w=length(b)-length(x);"
   "r=length(z)-length(e);"
   "u=length(d)-length(y);"
   "i=normalize(float3(w,r,u));"
   "return i;"
 "}"
 "float n(inout float3 f,float3 c,float4 w,float n)"
 "{"
   "float i,r=0.f;"
   "i=n;"
   "while(i>=n&&r<3.)"
     "{"
       "float4 x=float4(f,0),b=float4(1,0,0,0);"
       "float u=0.f;"
       "uint z=0;"
       "while(u<10&&z<10)"
         "b=2.f*t(x,b),x=t(x)+w,u=dot(x,x),z++;"
       "float d=length(x);"
       "i=.5f*d*log(d)/length(b);"
       "f+=c*i;"
       "r=dot(f,f);"
     "}"
   "return i;"
 "}"
 "float3 t(float3 f,float3 c,float3 x,float3 i)"
 "{"
   "float3 r=float3(1.,.45,.25);"
   "const int b=10;"
   "const float z=.45;"
   "float3 n=normalize(f-x),u=normalize(c-x);"
   "float w=dot(i,n);"
   "float3 d=n-2*w*i;"
   "r=c_diffuse.xyz+abs(i)*.3;"
   "return r*max(w,0)+z*pow(max(dot(u,d),0),b);"
 "}"
 "float3 h(float3 f,float3 c)"
 "{"
   "float i,x,r,u,w,n;"
   "i=2*dot(f,c);"
   "x=dot(f,f)-3.;"
   "r=sqrt(i*i-4*x);"
   "u=(-i+r)*.5;"
   "w=(-i-r)*.5;"
   "n=min(u,w);"
   "f+=n*c;"
   "return f;"
 "}"
 "float4 h(float3 f,float3 c,float4 x,float w,float3 i,float3 u,bool b)"
 "{"
   "const float4 z=float4(.3,.3,.3,0);"
   "float4 r;"
   "r=z;"
   "c=normalize(c);"
   "f=h(f,c);"
   "float d=n(f,c,x,w);"
   "if(d<w)"
     "{"
       "float3 e=n(f,x);"
       "r.xyz=t(u,c,f,e);"
       "r.w=1;"
       "if(b==true)"
         "{"
           "float3 y=normalize(u-f);"
           "f+=e*w*2.;"
           "d=n(f,y,x,w);"
           "if(d<w)"
             "r.xyz*=.4;"
         "}"
     "}"
   "return r;"
 "}"
 "[numthreads(4,64,1)]"
 "void main(uint3 c:SV_GroupID,uint3 i:SV_DispatchThreadID,uint3 r:SV_GroupThreadID,uint n:SV_GroupIndex)"
 "{"
   "float4 x=float4((float)i.x,(float)i.y,0.f,0.f);"
   "float2 w=float2(c_width,c_height);"
   "float z=min(w.x,w.y);"
   "float2 d=float2(.5f,.5f),u=(x.xy-d*w)/z*3.*zoom;"
   "float3 b=float3(1.5f,.5f,4.f),y=float3(0.f,0.f,4.f),e=float3(u.x,u.y,0.f);"
   "b=mul(float4(b,0.),rotation).xyz;"
   "y=mul(float4(y,0.),rotation).xyz;"
   "e=mul(float4(e,0.),rotation).xyz;"
   "float3 m=y,D=e-m;"
   "float4 l=h(m,D,c_mu,c_epsilon,y,b,c_selfShadow);"
   "f[i.xy]=l;"
 "}";

#endif // QJULIA_H_TMP_
