/* File generated with Shader Minifier 1.1.4
 * http://www.ctrl-alt-test.fr
 */
#ifndef ROADTOHELL_SHADER_H_H_TMP_
# define ROADTOHELL_SHADER_H_H_TMP_
# define VAR_PI "f"
# define VAR_OUTPUT "r"

static const char roadtohell_shader_h[] =
 "static const float f=3.14159f;"
 "RWTexture2D<float4> r:register(u0);cbuffer cb:register(b0){float2 _r;float _t;};"
 "void p(out float3 f,out float3 r,in float m,in float x)"
 "{"
   "float c=.3*_t+10.*x;"
   "f=float3(1.f,10.f,2.f);"
   "r=float3(0.,0.,0.);"
 "}"
 "float3 p()"
 "{"
   "return float3(0.,0.,0.);"
 "}"
 "float p(float f)"
 "{"
   "return frac(sin(f)*43758.5f);"
 "}"
 "float n(in float3 f)"
 "{"
   "float3 m=floor(f),r=frac(f);"
   "r=r*r*(3.-2.*r);"
   "float i=m.x+m.y*157.+113.*m.z;"
   "return lerp(lerp(lerp(p(i),p(i+1.),r.x),lerp(p(i+157.),p(i+158.),r.x),r.y),lerp(lerp(p(i+113.),p(i+114.),r.x),lerp(p(i+270.),p(i+271.),r.x),r.y),r.z);"
 "}"
 "float n(float f,float i)"
 "{"
   "return min(f,i);"
 "}"
 "float p(float f,float i)"
 "{"
   "return max(-f,i);"
 "}"
 "float e(float f,float i)"
 "{"
   "return max(f,i);"
 "}"
 "float2 x(float2 f,float2 i)"
 "{"
   "return f-i*floor(f/i);"
 "}"
 "float3 m(float3 f,float3 i)"
 "{"
   "return f-i*floor(f/i);"
 "}"
 "float3 i(float3 f,float3 i)"
 "{"
   "float3 r=m(f,i)-.5f*i;"
   "return float3(r.x,r.y,f.z);"
 "}"
 "float e(float3 f)"
 "{"
   "return length(f)-1.;"
 "}"
 "float l(float3 f,float3 i)"
 "{"
   "float3 r=abs(f)-i;"
   "return min(max(r.x,max(r.y,r.z)),0.)+length(max(r,0.));"
 "}"
 "float i(float3 f)"
 "{"
   "return n(e(f),l(i(f,float3(3.f,3.f,1000.f)),float3(1.f,1.f,1.f)))+.1*n(3.f*f);"
 "}"
 "float3 c(in float3 f,in float3 i)"
 "{"
   "return float3(.2,.07,.01);"
 "}"
 "float s(in float3 f,in float3 m)"
 "{"
   "const float r=20.,n=.001;"
   "float c=n*2.,x=0.,l=-1.;"
   "for(int p=0;p<90;p++)"
     "{"
       "if(c<n||x>r)"
         "break;"
       "c=i(f+m*x);"
       "x+=c;"
     "}"
   "if(x<r)"
     "l=x;"
   "return l;"
 "}"
 "float3 c(in float3 f)"
 "{"
   "const float i=.002;"
   "const float3 r=float3(1.,-1.,-1.),l=float3(-1.,-1.,1.),m=float3(-1.,1.,-1.),c=float3(1.,1.,1.);"
   "return normalize(r*e(f+r*i)+l*e(f+l*i)+m*e(f+m*i)+c*e(f+c*i));"
 "}"
 "float h(in float3 f,in float3 i)"
 "{"
   "float r=1.,x=.0005,l=1.;"
   "for(int c=0;c<40;c++)"
     "l=e(f+i*x),r=min(r,64.*l/x),x+=clamp(l,.02,2.);"
   "return clamp(r,0.,1.);"
 "}"
 "float3 c(in float3 f,in float3 i,in float3 r,in float x,in float3 m)"
 "{"
   "float3 c=float3(0.f,0.f,0.f),l=normalize(float3(1.,.7,.9));"
   "float n=max(dot(i,l),0.),p=0.;"
   "if(n>.01)"
     "p=h(f+.01*i,l);"
   "c+=n*float3(4.,4.,4.)*p;"
   "c+=float3(.5,.5,.5);"
   "float3 y=m*c;"
   "y*=exp(-.01*x*x);"
   "return y;"
 "}"
 "float3x3 c(in float3 f,in float3 i,in float r)"
 "{"
   "float3 l=normalize(i-f),c=normalize(cross(l,float3(sin(r),cos(r),0.))),x=normalize(cross(c,l));"
   "return float3x3(c,x,l);"
 "}"
 "[numthreads(8,8,1)]"
 "void main(uint3 f:SV_DispatchThreadID)"
 "{"
   "float2 i=float2(f.xy),l=(-_r.xy+2.*i.xy)/_r.y,m=float2(0.f,0.f),x=m.xy/_r.xy;"
   "float3 n,y;"
   "p(n,y,_t,x.x);"
   "float3x3 u=c(n,y,0.);"
   "float3 z=normalize(mul(u,float3(l.xy,2.))),o=p();"
   "float e=s(n,z);"
   "if(e>-.5)"
     "{"
       "float3 h=n+e*z,t=c(h),D=c(h,t);"
       "o=c(h,t,z,e,D);"
     "}"
   "float3 h=pow(clamp(o,0.,1.),float3(.4545f,.4545f,.4545f));"
   "r[f.xy]=float4(h.x,h.y,h.z,1.f);"
 "}";

#endif // ROADTOHELL_SHADER_H_H_TMP_
