#ifndef SOUND_HPP
#define SOUND_HPP
#define MZK_DURATION    60
#define MZK_RATE        44100
#define MZK_NUMCHANNELS 2
#define MZK_NUMSAMPLES  (MZK_DURATION*MZK_RATE)
#define MZK_NUMSAMPLES_CHANNELS (MZK_NUMSAMPLES*MZK_NUMCHANNELS)
#define MZK_THREAD_NUM 65536
#endif /* SOUND_HPP */

