#pragma once
#define MZK_DURATION    22
#define MZK_RATE        44100
#define MZK_NUMCHANNELS 2
#define MZK_NUMSAMPLES  (MZK_DURATION*MZK_RATE)
#define MZK_NUMSAMPLESC (MZK_NUMSAMPLES*MZK_NUMCHANNELS)

